server:
  port: 8083  # Event:8081, Payment:8082, Notification:8083

spring:
  application:
    name: notification-service
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


kafka:
  topics:
    reservation-initiation: reservation-initiation-topic
    payment-success: payment-success-topic
    payment-failure: payment-failure-topic


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/