version: '3.8'

services:
  #  EVENT SERVICE DB

  event-db:
    image: postgres:15-alpine
    container_name: ticket-event-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ticket_db
    ports:
      - "5432:5432"
    volumes:
      - event_db_data:/var/lib/postgresql/data
    networks:
      - ticket-network


  # PAYMENT SERVICE DB

  payment-db:
    image: postgres:15-alpine
    container_name: ticket-payment-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=payment_db
    ports:
      - "5433:5432"
    volumes:
      - payment_db_data:/var/lib/postgresql/data
    networks:
      - ticket-network

  user-db:
    image: postgres:15
    container_name: ticket-user-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=user_db
    ports:
      - "5434:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - ticket-network


  # EVENT SERVICE (Backend)

  event-service:
    profiles: ["app"]
    build: ./event-service
    container_name: ticket-event-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://event-db:5432/ticket_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_DATA_REDIS_HOST=redis
    depends_on:
      - event-db
      - kafka
      - redis
    networks:
      - ticket-network

  # PAYMENT SERVICE (Backend)

  payment-service:
    profiles: ["app"]
    build: ./payment-service
    container_name: ticket-payment-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://payment-db:5432/payment_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - payment-db
      - kafka
    networks:
      - ticket-network

  # ORTAK ALTYAPI (Redis, Kafka, Zookeeper)

  redis:
    image: redis:alpine
    container_name: ticket-redis
    ports:
      - "6379:6379"
    networks:
      - ticket-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: ticket-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - ticket-network

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: ticket-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - ticket-network

  zipkin:
    image: openzipkin/zipkin
    container_name: ticket-zipkin
    ports:
      - "9411:9411"
    networks:
      - ticket-network

  #  METRICS (Prometheus)

  prometheus:
    image: prom/prometheus
    container_name: ticket-prometheus
    ports:
      - "9090:9090" # Prometheus Arayüz Portu
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml # Config dosyasını içeri atıyoruz
    extra_hosts:
      - "host.docker.internal:host-gateway" # Mac/Linux için kritik ayar! (Localhost'a erişim izni)
    networks:
      - ticket-network


  #  VISUALIZATION (Grafana)

  grafana:
    image: grafana/grafana
    container_name: ticket-grafana
    ports:
      - "3000:3000" # Grafana Arayüz Portu
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin # Giriş şifresi
    networks:
      - ticket-network
    depends_on:
      - prometheus

volumes:
  event_db_data:
  payment_db_data:
  user_db_data:

networks:
  ticket-network:
    driver: bridge