server:
  port: 8080

spring:
  application:
    name: api-gateway
  reactor:
    context-propagation: auto
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        # 1. USER SERVICE (BASİT YÖNTEM)
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            # DİKKAT: Artık "/users/**" diye bekliyoruz (/api yok)
            - Path=/users/**
          filters:
            - StripPrefix=1 # "/users" kısmını siler, gerisini gönderir
            # Circuit Breaker şimdilik kapalı kalsın (kafa karıştırmasın)

        # 2. EVENT SERVICE
        - id: event-service
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/events/**
          filters:
            - AuthenticationFilter
#            - StripPrefix=1

        # 3. PAYMENT SERVICE
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**
          filters:
            - AuthenticationFilter
#            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true


resilience4j:
  circuitbreaker:
    configs:
      default: # Tüm servisler için varsayılan ayar
        registerHealthIndicator: true # Actuator /health endpoint'inde durumu göster

        # 1. Kayan Pencere (Sliding Window)
        slidingWindowType: COUNT_BASED # Son X isteğe bak (TIME_BASED de olabilir)
        slidingWindowSize: 10 # Son 10 isteği analiz et

        # 2. Hata Eşiği (Threshold)
        failureRateThreshold: 50 # %50 hata alırsak (10 isteğin 5'i patlarsa) sigortayı attır

        # 3. Yavaşlık Eşiği (Slow Call)
        slowCallRateThreshold: 50 # İsteklerin %50'si yavaşsa da sigortayı attır
        slowCallDurationThreshold: 2s # 2 saniyeden uzun süren istek "yavaş" sayılır

        # 4. Bekleme ve Test Süreçleri
        waitDurationInOpenState: 10s # OPEN durumuna geçince 10 saniye bekle (Servise nefes aldır)
        permittedNumberOfCallsInHalfOpenState: 3 # 10 sn sonra, HALF-OPEN modunda 3 deneme isteği at

        # 5. Otomatik Geçiş
        automaticTransitionFromOpenToHalfOpenEnabled: true # Süre dolunca otomatik HALF-OPEN ol

    instances:
      eventService:
        baseConfig: default # Yukarıdaki default ayarları kullan
      paymentService:
        baseConfig: default
      userService:
        baseConfig: default

  # ZAMAN AŞIMI AYARLARI (TimeLimiter)
  timelimiter:
    configs:
      default:
        timeoutDuration: 3s # Bir servis 3 saniye cevap vermezse kesip at (Timeout Exception)

# Actuator 
management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, circuitbreakers
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: "w3c,b3"
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  observations:
    http:
      server:
        requests:
          ignore-patterns: "/actuator/**"

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"






