name: User Service CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'user-service/**'

jobs:
  call-workflow:
    uses: ./.github/workflows/ci-template.yml
    with:
      service_name: user-service
    secrets: inherit